Add xl food mod compatibility
AgriCraft/AgriPlants pull request #68
Opened 2021-05-16 12:48 UTC by nbrichau

2021-05-16 21:34 UTC, InfinityRaider requested changes

2021-05-16 21:34 UTC, InfinityRaider commented on mod_xlfoodmod/plants/lettuce_plant.json
> +  "id": "xlfoodmod:lettuce_agriplant",
Just "_plant" as suffix is good enough.

2021-05-16 21:34 UTC, InfinityRaider commented on mod_xlfoodmod/plants/onion_plant.json
> +  "seed_lang_key": "item.xlfoodmod.onion",
Same lang keys for seed and description?

2021-05-16 21:34 UTC, InfinityRaider commented on mod_xlfoodmod/plants/rice_plant.json
> +      "object": "minecraft:empty",
Not water for rice?

2021-05-16 22:45 UTC, nbrichau commented on mod_xlfoodmod/plants/lettuce_plant.json
> +  "id": "xlfoodmod:lettuce_agriplant",
That's not possible to have "_plant" as suffix because xlfoodmod already use this one for their blocks ("xlfoodmod:lettuce_plant" for the lettuce block)

2021-05-16 22:46 UTC, nbrichau commented on mod_xlfoodmod/plants/rice_plant.json
> +      "object": "minecraft:empty",
Yes, the original crop don't need water.

2021-05-16 22:50 UTC, nbrichau commented on mod_xlfoodmod/plants/onion_plant.json
> +  "seed_lang_key": "item.xlfoodmod.onion",
When there are no description for the plant, I take the name of the product as the description, like in 1.12.
As the onion item (product) is also the seed, they share the same lang key

2021-05-17 05:48 UTC, InfinityRaider commented on mod_xlfoodmod/plants/lettuce_plant.json
> +  "id": "xlfoodmod:lettuce_agriplant",
Is that an issue? These plants sit in a different registry.

2021-05-17 05:48 UTC, InfinityRaider commented on mod_xlfoodmod/plants/onion_plant.json
> +  "seed_lang_key": "item.xlfoodmod.onion",
Ok

2021-05-17 05:48 UTC, InfinityRaider commented on mod_xlfoodmod/plants/rice_plant.json
> +      "object": "minecraft:empty",
Hmmmmm

2021-05-17 08:40 UTC, nbrichau commented on mod_xlfoodmod/plants/lettuce_plant.json
> +  "id": "xlfoodmod:lettuce_agriplant",
Oh you're right, different registry, that shouldn't cause any problem then

2021-05-18 21:21 UTC, merged